name: CI
on: [push, pull_request]
jobs:
  linting-tests:
    name: Rubocop
    runs-on: ubuntu-20.04 # ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install Rubocop
        run: gem install rubocop
      - name: Run Rubocop
        run: rubocop app
  audit:
    name: Audit
    runs-on: ubuntu-20.04 # ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install Bundler Audit & Brakeman
        run: |
          gem install bundler:2.2.5
          gem install bundler-audit
          gem install brakeman
      - name: Audit Dependencies
        run: |
          bundler-audit --update
          brakeman -q -w2
  unit-tests:
    name: RSpec
    runs-on: ubuntu-20.04 # ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Bundler
        run: gem install bundler
      - name: Install Gems
        run: bundle install --path vendor/bundle
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - name: Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install JS Packages
        run: yarn install --pure-lockfile
      - name: Install Rails
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get install libpq-dev
          cp config/database.github.yml config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
      - name: Run RSpec
        run: bundle exec rspec