name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        # The postgres container requires the postgres user to be setup with a password in order to start it due to security
        # reasons
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      # RUBY
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      # BUNDLER
      - name: Setup Bundler
        run: gem install bundler:2.2.5
      # NODE
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      # RAILS
      - name: Setup Rails
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle install --no-deployment --jobs 4 --retry 3
          cp config/database.github.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
          yarn --frozen-lockfile
      - name: RSpec
        run: bundle exec rspec