name: Test
on: [push, pull_request]
jobs:
  linting-tests:
    name: Rubocop
    runs-on: ubuntu-20.04 # ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.0.0
      - name: Install Rubocop
        run: gem install rubocop
      - name: Run linter
        run: rubocop app
  unit-tests:
    name: RSpec
    needs: linting-tests # require linting to pass first
    runs-on: ubuntu-20.04 # ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.0.0
      - name: Install Postgres Client
        run: sudo apt-get install libpq-dev
      - name: Ruby gems cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake # rspec